server:
  port: 8080

tomcat:
  uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/rice?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false

mybatis:
  mapper-locations: "classpath:/mybatis/mapper/*.xml"


